### ISSUE TITLE
Compilation error on mac

### ISSUE THREAD

**Issue by AndreaBulgarelli** [AGILESCIENCE/libagilesci#1]
@azoli 
g++  -fexceptions -g -O2 -pipe -Wno-parentheses -Wno-unused-parameter -I/Users/bulgarelli/local.agile//include -I/Users/bulgarelli/local.agile//include -I/Users/bulgarelli/local.agile//include -I include  -I/opt/local/include -pthread -stdlib=libc++ -std=c++1y -m64 -I/opt/local/libexec/root6/include/root -W -fPIC -D_REENTRANT -c src/RoiMulti5.cpp -o obj/RoiMulti5.o
src/RoiMulti5.cpp:343:2: error: initializer 'm_fluxScaleFactorMulInv' does not name a non-static data member or base class; did you mean the member
      'm_fluxScaleFactor'?
        m_fluxScaleFactorMulInv(0.0),
        ^~~~~~~~~~~~~~~~~~~~~~~
        m_fluxScaleFactor
/Users/bulgarelli/local.agile//include/RoiMulti5.h:613:9: note: 'm_fluxScaleFactor' declared here
        double m_fluxScaleFactor;
               ^
src/RoiMulti5.cpp:345:2: error: member initializer 'm_status' does not name a non-static data member or base class
        m_status(-1),
        ^~~~~~~~~~~~
src/RoiMulti5.cpp:346:2: error: member initializer 'm_cts' does not name a non-static data member or base class
        m_cts(-1),
        ^~~~~~~~~
src/RoiMulti5.cpp:347:2: error: initializer 'm_ctsMove' does not name a non-static data member or base class; did you mean the member 'm_ctsMaps'?
        m_ctsMove(-1),
        ^~~~~~~~~
        m_ctsMaps
/Users/bulgarelli/local.agile//include/RoiMulti5.h:545:12: note: 'm_ctsMaps' declared here
        AgileMap\* m_ctsMaps;
                  ^
src/RoiMulti5.cpp:347:2: error: cannot initialize a member subobject of type 'AgileMap _' with an rvalue of type 'int'
        m_ctsMove(-1),
        ^         ~~
src/RoiMulti5.cpp:349:5: error: member initializer 'm_galLimitMin' does not name a non-static data member or base class
    m_galLimitMin(0.0),
    ^~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:350:5: error: member initializer 'm_galLimitMax' does not name a non-static data member or base class
    m_galLimitMax(100.0),
    ^~~~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:351:5: error: member initializer 'm_isoLimitMin' does not name a non-static data member or base class
    m_isoLimitMin(0.0),
    ^~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:352:5: error: member initializer 'm_isoLimitMax' does not name a non-static data member or base class
    m_isoLimitMax(100.0),
    ^~~~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:353:5: error: member initializer 'm_extLimitMin' does not name a non-static data member or base class
    m_extLimitMin(0.0),
    ^~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:354:5: error: member initializer 'm_extLimitMax' does not name a non-static data member or base class
    m_extLimitMax(1000.0),
    ^~~~~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:355:5: error: member initializer 'm_fluxLimitMin' does not name a non-static data member or base class
    m_fluxLimitMin(0.0),
    ^~~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:356:5: error: member initializer 'm_fluxLimitMax' does not name a non-static data member or base class
    m_fluxLimitMax(FLUX_UPPER_BOUND),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:357:5: error: member initializer 'm_indexLimitMin' does not name a non-static data member or base class
    m_indexLimitMin(0.5),
    ^~~~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:358:5: error: member initializer 'm_indexLimitMax' does not name a non-static data member or base class
    m_indexLimitMax(5.0)
    ^~~~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:343:2: error: multiple initializations given for non-static member 'm_fluxScaleFactor'
        m_fluxScaleFactorMulInv(0.0),
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:342:2: note: previous initialization is here
        m_fluxScaleFactor(0.0),
        ^~~~~~~~~~~~~~~~~~~~~~
src/RoiMulti5.cpp:1027:1: error: use of undeclared identifier 'm_ctsMove'; did you mean 'm_ctsMaps'?
m_ctsMove = 0;
^~~~~~~~~
m_ctsMaps
/Users/bulgarelli/local.agile//include/RoiMulti5.h:545:12: note: 'm_ctsMaps' declared here
        AgileMap_ m_ctsMaps;
                  ^
src/RoiMulti5.cpp:1030:9: error: use of undeclared identifier 'm_ctsMove'; did you mean 'm_ctsMaps'?
        m_ctsMove += m_ctsMaps[0](r,c);
        ^~~~~~~~~
        m_ctsMaps
/Users/bulgarelli/local.agile//include/RoiMulti5.h:545:12: note: 'm_ctsMaps' declared here
        AgileMap\* m_ctsMaps;
                  ^
src/RoiMulti5.cpp:1030:19: error: invalid operands to binary expression ('AgileMap *' and 'double')
        m_ctsMove += m_ctsMaps[0](r,c);
        ~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by azoli** [comment]
Sta usando il .h presente nella cartella di installazione, prova a rifare l'installazione su un prefix pulito.

**Comment by AndreaBulgarelli** [comment]
Risolto
